include: package:pedantic/analysis_options.1.9.0.yaml

analyzer:
  exclude:
    - lib/app_level/generated/**
  errors:
    missing_required_param: error
    missing_return: warning
    undefined_prefixed_name: ignore

linter:
  rules:
    - camel_case_types
