name: eliud_pkg_shop
description: Eliud shop package
homepage: https://eliud.io
repository: https://github.com/eliudio/eliud

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.1.0
  cloud_firestore: ^4.6.0
  collection: ^1.17.0
  datetime_picker_formfield: ^2.0.0
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  http: ^0.13.5
#  image: ^4.0.17
  intl: ^0.18.1
  meta: ^1.8.0
#  path: ^1.8.2
#  tuple: ^2.0.1
  transparent_image: ^2.0.0

  eliud_core: ^1.0.0
  eliud_pkg_fundamentals: ^1.0.0
  eliud_pkg_pay: ^1.0.0
  eliud_pkg_notifications: ^1.0.0
  eliud_pkg_workflow: ^1.0.0

dev_dependencies:
  build_runner: ^2.1.0

  eliud_generator: ^1.0.0

flutter:
  uses-material-design: true

platforms:
  android:
  ios:
  web:
