---
name: eliud_pkg_shop
description: eliud_pkg_shop is a package to provide shop functionality to your eliud
  app. More info at https://eliud.io
homepage: https://eliud.io
repository: https://github.com/eliudio/eliud_pkg_shop
version: 1.1.6
environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.0.0'
dependencies:
  eliud_core_main: ^1.0.2
  eliud_pkg_pay: ^1.2.0
  eliud_pkg_shop_model: ^1.1.6
  eliud_core_helpers: ^1.0.0
  eliud_core: ^1.1.6
  eliud_core_model: ^1.0.0
  eliud_pkg_workflow: ^1.1.6
  eliud_pkg_workflow_model: ^1.0.0
  eliud_pkg_fundamentals: ^1.1.7
  eliud_pkg_notifications: ^1.1.6
  eliud_pkg_fundamentals_model: ^1.0.0
  bloc: ^8.1.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  cloud_firestore: ^4.13.5
  intl: 0.19.0
  meta: ^1.10.0
  flutter:
    sdk: flutter
dev_dependencies:
  lints: ^3.0.0
flutter:
  uses-material-design: true
platforms:
  android: null
  ios: null
  web: null
