name: eliud_pkg_shop
description: Eliud shop package
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  eliud_model:
    path: ../eliud_model

  stripe_payment: 1.0.7
  cloud_functions: 0.4.1+8

dev_dependencies:
  build_runner: "1.10.2"

  eliud_generator:
    path: ../eliud_generator

flutter:
