name: eliud_pkg_shop
description: Eliud shop package
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  eliud_core:
    path: ../eliud_core

  eliud_pkg_fundamentals:
    path: ../eliud_pkg_fundamentals

  eliud_pkg_pay:
    path: ../eliud_pkg_pay

  eliud_pkg_workflow:
    path: ../eliud_pkg_workflow

  eliud_pkg_medium:
    path: ../eliud_pkg_medium

dev_dependencies:
  build_runner: "1.11.5"

  eliud_generator:
    path: ../eliud_generator

flutter:
  uses-material-design: true

  assets:
    - packages/eliud_pkg_shop/assets/shop/decorating/charlotte_sitting.png
    - packages/eliud_pkg_shop/assets/shop/decorating/charlotte_standing.png
    - packages/eliud_pkg_shop/assets/shop/decorating/charlotte_with_credit_card.png
    - packages/eliud_pkg_shop/assets/shop/decorating/charlotte_presenting.png
    - packages/eliud_pkg_shop/assets/shop/decorating/charlotte_with_bags.png
    - packages/eliud_pkg_shop/assets/shop/products/gouldianfinch1.png
    - packages/eliud_pkg_shop/assets/shop/products/gouldianfinch2.png
    - packages/eliud_pkg_shop/assets/shop/products/redbreastedblackbird1.png
    - packages/eliud_pkg_shop/assets/shop/products/redbreastedblackbird2.png
    - packages/eliud_pkg_shop/assets/shop/products/queenofthenight1.png
    - packages/eliud_pkg_shop/assets/shop/products/queenofthenight2.png
    - packages/eliud_pkg_shop/assets/shop/products/goldenoriole1.png
    - packages/eliud_pkg_shop/assets/shop/products/goldenoriole2.png
    - packages/eliud_pkg_shop/assets/shop/products/turquoisekakariki1.png
    - packages/eliud_pkg_shop/assets/shop/products/turquoisekakariki2.png
    - packages/eliud_pkg_shop/assets/shop/products/amaryllis1.png
    - packages/eliud_pkg_shop/assets/shop/products/amaryllis2.png
    - packages/eliud_pkg_shop/assets/shop/products/daisy1.png
    - packages/eliud_pkg_shop/assets/shop/products/daisy2.png
    - packages/eliud_pkg_shop/assets/shop/products/anemone1.png
    - packages/eliud_pkg_shop/assets/shop/products/anemone2.png
    - packages/eliud_pkg_shop/assets/shop/products/lilyofthenile1.png
    - packages/eliud_pkg_shop/assets/shop/products/lilyofthenile2.png
    - packages/eliud_pkg_shop/assets/shop/products/bluebackedmanakin1.png
    - packages/eliud_pkg_shop/assets/shop/products/bluebackedmanakin2.png
    - packages/eliud_pkg_shop/assets/shop/products/northerncardinal1.png
    - packages/eliud_pkg_shop/assets/shop/products/northerncardinal2.png
    - packages/eliud_pkg_shop/assets/shop/products/eurasianmagpie1.png
    - packages/eliud_pkg_shop/assets/shop/products/eurasianmagpie2.png
    - packages/eliud_pkg_shop/assets/shop/products/myna1.png
    - packages/eliud_pkg_shop/assets/shop/products/myna2.png
    - packages/eliud_pkg_shop/assets/shop/products/parakeet1.png
    - packages/eliud_pkg_shop/assets/shop/products/parakeet2.png
    - packages/eliud_pkg_shop/assets/shop/products/kingbird1.png
    - packages/eliud_pkg_shop/assets/shop/products/kingbird2.png
    - packages/eliud_pkg_shop/assets/shop/products/grosbeak1.png
    - packages/eliud_pkg_shop/assets/shop/products/grosbeak2.png
    - packages/eliud_pkg_shop/assets/shop/logo/day30-cafe.png
