---
name: eliud_pkg_shop
description: eliud_pkg_shop is a package to provide shop functionality to your eliud
  app. More info at https://eliud.io
homepage: https://eliud.io
repository: https://github.com/eliudio/eliud_pkg_shop
version: 1.1.5+10
environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.0.0'
dependencies:
  eliud_core_main:                                                                                   # ANDROID IOS             WEB
    path: ../eliud_core_main
  eliud_pkg_pay:                                                                                     # ANDROID IOS             WEB
    path: ../eliud_pkg_pay
  eliud_pkg_shop_model:                                                                              # ANDROID IOS             WEB
    path: ../eliud_pkg_shop_model

  flutter:
    sdk: flutter
dev_dependencies:
  lints: ^3.0.0
flutter:
  uses-material-design: true
platforms:
  android: null
  ios: null
  web: null
