---
name: eliud_pkg_shop
description: eliud_pkg_shop is a package to provide shop functionality to your eliud
  app. More info at https://eliud.io
homepage: https://eliud.io
repository: https://github.com/eliudio/eliud_pkg_shop
version: 1.1.5+10
environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'
dependencies:
  bloc: ^8.1.2
  cloud_firestore: ^4.12.2
  collection: ^1.17.2
  eliud_core: ^1.1.5+7
  eliud_pkg_fundamentals: ^1.0.0
  eliud_pkg_pay: ^1.1.5+5
  eliud_pkg_notifications: ^1.1.5+5
  eliud_pkg_workflow: ^1.1.5+5
  eliud_pkg_shop_model: ^1.1.5+10
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  intl: ^0.18.1
  meta: ^1.9.1
  transparent_image: ^2.0.1
  flutter:
    sdk: flutter
dev_dependencies:
  lints: ^3.0.0
flutter:
  uses-material-design: true
platforms:
  android: null
  ios: null
  web: null
